import os
import json

from dotenv import load_dotenv
from google import genai

from app.services.metadata import load_data_dictionary
from app.core.planner_schema import QueryPlan


load_dotenv()


API_KEY = os.getenv("OPENAI_API_KEY")

if not API_KEY:
    raise RuntimeError(
        "Gemini API key is not configured."
    )


client = genai.Client(
    api_key=API_KEY
)


def clean_json_response(text):

    text = text.strip()

    if text.startswith("```json"):
        text = text[7:]

    elif text.startswith("```"):
        text = text[3:]

    if text.endswith("```"):
        text = text[:-3]

    return text.strip()


def create_query_plan(user_query: str) -> QueryPlan:

    if not user_query or not user_query.strip():
        raise ValueError(
            "Query cannot be empty."
        )

    data_dictionary = load_data_dictionary()

    prompt = f"""
You are a business analytics query planner.

Convert the user's natural language query into a structured query plan.

Data dictionary:
{json.dumps(data_dictionary, indent=2)}

Allowed operations:
- sum
- average
- count
- ranking
- contribution
- comparison

Allowed comparisons:
- target
- yoy

Important rules:

1. Return ONLY valid JSON.
2. The metric must be a valid metric from the data dictionary.
3. Dimensions must be valid data dimensions.
4. Filters must ALWAYS be objects with "column" and "value".
5. Do NOT return filters as strings.
6. If there is no filter, return an empty list.
7. limit must be a positive number or null.
8. comparison must be "target", "yoy", or null.
9. If the user asks for contribution percentage, contribution %, share of total, or percentage contribution, use operation "contribution".
10. If the user asks for ranking or top N, use operation "ranking".
11. Ranking must include a dimension and a positive limit.
12. If the user mentions a month such as January, February, March, Jan, Feb, or Mar, use the "month" column with the format "YYYY-MM".
13. The dataset contains only 2024 data:
    January = 2024-01
    February = 2024-02
    March = 2024-03
14. For target comparison queries such as "which region missed its target", use:
    operation = "comparison"
    comparison = "target"
    dimension = "region"
15. If the user says "customer" or "customers", use "customer_id".
16. Do NOT use "customer_segment" unless the user explicitly says:
    customer segment
    segment
    consumer
    corporate
    home office
17. For "top N customers per region", use:
    dimensions = ["region", "customer_id"]
    operation = "ranking"
    limit = N
18. Do not invent fields that are not present in the data dictionary.

Required JSON structure:

{{
    "metric": "revenue",
    "dimensions": [],
    "filters": [],
    "operation": "sum",
    "limit": null,
    "comparison": null
}}

User query:
{user_query}
"""

    try:

        response = client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt
        )

    except Exception as error:

        raise RuntimeError(
            f"Unable to contact Gemini: {error}"
        )


    if not response or not response.text:

        raise RuntimeError(
            "Gemini returned an empty response."
        )


    result = clean_json_response(
        response.text
    )


    try:

        plan_data = json.loads(result)

    except json.JSONDecodeError:

        raise ValueError(
            "Gemini returned an invalid query plan."
        )


    if not isinstance(plan_data, dict):

        raise ValueError(
            "Gemini query plan must be a JSON object."
        )


    try:

        return QueryPlan(**plan_data)

    except Exception as error:

        raise ValueError(
            f"Invalid query plan generated by Gemini: {error}"
        )